# -*- coding: utf-8 -*-
from __future__ import print_function

import argparse
import io
import os
import re

ROOT = os.path.abspath(os.path.dirname(__file__))
SRC = os.path.join(ROOT, "faqs", "Frequently-Asked-Questions.md")

LINK_RE = re.compile(r'\[([^\]]+)\]\(([^)]+)\)')
CODE_RE = re.compile(r'`([^`]+)`')
HR_RE = re.compile(r'^\s*([*_-])\1\1+\s*$')


def convert(md_text):
    lines = md_text.splitlines()
    out = []

    # Title
    i = 0
    if lines and lines[0].startswith("# "):
        title = lines[0][2:].strip()
        out.append(title)
        out.append("=" * len(title))
        out.append("")
        i = 1
        if i < len(lines) and lines[i].strip() == "":
            i += 1

    for line in lines[i:]:
        if HR_RE.match(line):
            if out and out[-1].strip():
                out.append("")
            out.append("----")
            out.append("")
            continue

        # Image on its own line
        stripped = line.strip()
        if stripped.startswith("![") and stripped.endswith(")"):
            m = re.match(r'!\[([^\]]*)\]\(([^)]+)\)', stripped)
            if m:
                alt, url = m.group(1), m.group(2)
                if out and out[-1].strip():
                    out.append("")
                out.append(".. image:: %s" % url)
                if alt:
                    out.append("   :alt: %s" % alt)
                out.append("")
                continue

        # Inline code
        line = CODE_RE.sub(r'``\1``', line)
        # Markdown links
        line = LINK_RE.sub(r'`\1 <\2>`_', line)

        out.append(line)

    return "\n".join(out) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate RST from FAQ markdown.")
    parser.add_argument(
        "--out-dir",
        required=True,
        help="Output directory for generated RST.",
    )
    args = parser.parse_args(argv)
    out_dir = os.path.abspath(args.out_dir)
    out_path = os.path.join(out_dir, "Frequently-Asked-Questions.rst")

    if not os.path.exists(SRC):
        print("Source not found: %s" % SRC)
        return 1

    if not os.path.isdir(out_dir):
        os.makedirs(out_dir)

    with io.open(SRC, "r", encoding="utf-8") as f:
        md_text = f.read()

    rst_text = convert(md_text)

    header = u".. This file is generated from %s. Do not edit directly.\n" % os.path.basename(SRC)
    header += u".. Generated by md_to_rst_faq.py\n\n"

    with io.open(out_path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write(rst_text)

    print("Wrote %s" % out_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
