name: Cross

on: [push, pull_request]

# Automatically cancel previous runs of this workflow on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cmake:
    # Skip building pull requests from the same repository
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Visual Studio Development Environment
        if: ${{ matrix.platform == 'windows-latest' }}
        uses: TheMrMilchmann/setup-msvc-dev@79dac248aac9d0059f86eae9d8b5bfab4e95e97c # v4.0.0
        with:
          arch: x64

      - name: Install Qt
        uses: jurplel/install-qt-action@48d3ad6db93f3627c8ee7a0454bc6f3744f7e730 # v4.3.1
        with:
          cache: true
          modules: qtwebsockets

      - name: Build
        run: |
          cd src/cross
          cmake -B build -G Ninja -DCMAKE_UNITY_BUILD=ON -DELFBUG_BUILD_TESTS=ON
          cmake --build build

      - name: Test ElfBug
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          sudo sysctl -w kernel.yama.ptrace_scope=0
          cd src/cross/build
          ctest --output-on-failure --no-tests=error

  appimage:
    # Skip building pull requests from the same repository
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/x64dbg/x64dbg/qt5-appimage
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Build AppImage
        run: |
          src/cross/debugger/build-appimage.sh

      - name: Upload AppImage
        uses: actions/upload-artifact@v7
        with:
          name: x64dbg-appimage
          path: src/cross/build-linux/x64dbg.AppImage
          if-no-files-found: error
          include-hidden-files: true
          retention-days: 1
